import { AppNotification, Category, Order, Product, UserProfile, Voucher } from '../types';

export const seedCategories: Category[] = [
  { id: 'phones-laptops', name: 'Dien thoai & Laptop', icon: 'Smartphone' },
  { id: 'fashion', name: 'Thoi trang', icon: 'Shirt' },
  { id: 'home-living', name: 'Gia dung', icon: 'Home' },
  { id: 'accessories', name: 'Phu kien so', icon: 'Headphones' },
  { id: 'beauty', name: 'Lam dep', icon: 'Sparkles' },
];

export const seedProducts: Product[] = [
  {
    id: 'p1',
    sku: 'IP15PM-256',
    name: 'iPhone 15 Pro Max 256GB chinh hang VN/A',
    brand: 'Apple',
    categoryId: 'phones-laptops',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
    ],
    originalPrice: 34990000,
    discountPrice: 29990000,
    flashSalePrice: 28990000,
    discountPercent: 14,
    rating: 4.8,
    reviewCount: 124,
    stock: 45,
    isBestSeller: true,
    description: 'Thiet ke titan, camera zoom quang hoc 5x, chip A17 Pro va bao hanh chinh hang.',
    attributes: [
      { name: 'Mau sac', values: ['Titan tu nhien', 'Titan den', 'Titan xanh'] },
      { name: 'Dung luong', values: ['256GB', '512GB', '1TB'] },
    ],
  },
  {
    id: 'p2',
    sku: 'S24U-256',
    name: 'Samsung Galaxy S24 Ultra 12GB/256GB AI Phone',
    brand: 'Samsung',
    categoryId: 'phones-laptops',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    originalPrice: 33990000,
    discountPrice: 26490000,
    flashSalePrice: 25990000,
    discountPercent: 22,
    rating: 4.7,
    reviewCount: 89,
    stock: 28,
    isNew: true,
    description: 'Man hinh Dynamic AMOLED 2X, S Pen, Galaxy AI va camera 200MP.',
    attributes: [{ name: 'Mau sac', values: ['Xam titan', 'Den titan', 'Tim titan'] }],
  },
  {
    id: 'p3',
    sku: 'MBA-M3-256',
    name: 'MacBook Air 13 inch M3 8GB/256GB',
    brand: 'Apple',
    categoryId: 'phones-laptops',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    originalPrice: 27990000,
    discountPrice: 25490000,
    discountPercent: 9,
    rating: 4.9,
    reviewCount: 42,
    stock: 15,
    isNew: true,
    description: 'Laptop mong nhe voi chip Apple M3, man hinh Liquid Retina va pin ca ngay.',
    attributes: [{ name: 'Mau sac', values: ['Xam', 'Bac', 'Vang'] }],
  },
  {
    id: 'p4',
    sku: 'WIND-BLOCKER',
    name: 'Ao khoac gio nam chong nuoc WindBlocker',
    brand: 'Coolmate',
    categoryId: 'fashion',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop&q=80',
    originalPrice: 550000,
    discountPrice: 299000,
    flashSalePrice: 199000,
    discountPercent: 45,
    rating: 4.5,
    reviewCount: 310,
    stock: 120,
    isBestSeller: true,
    description: 'Vai chong tham nhe, can gio tot, phu hop di mua nho hoac di phuot.',
    attributes: [
      { name: 'Mau sac', values: ['Den', 'Xanh than', 'Reu'] },
      { name: 'Kich co', values: ['M', 'L', 'XL'] },
    ],
  },
  {
    id: 'p5',
    sku: 'SONY-XM5',
    name: 'Tai nghe chong on Sony WH-1000XM5',
    brand: 'Sony',
    categoryId: 'accessories',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    originalPrice: 8490000,
    discountPrice: 6990000,
    discountPercent: 17,
    rating: 4.8,
    reviewCount: 75,
    stock: 22,
    description: 'Chong on chu dong, am thanh hi-res va thoi luong pin len den 30 gio.',
    attributes: [{ name: 'Mau sac', values: ['Den', 'Bac', 'Xanh navy'] }],
  },
  {
    id: 'p6',
    sku: 'TEFAL-EASYFRY',
    name: 'Noi chien khong dau Tefal Easy Fry 4.2L',
    brand: 'Tefal',
    categoryId: 'home-living',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80',
    originalPrice: 4390000,
    discountPrice: 2190000,
    flashSalePrice: 1890000,
    discountPercent: 50,
    rating: 4.7,
    reviewCount: 160,
    stock: 35,
    isBestSeller: true,
    description: 'Dung tich 4.2L, chien nuong tien loi va de ve sinh cho gia dinh.',
    attributes: [{ name: 'Phien ban', values: ['Co dien', 'Cam ung'] }],
  },
];

export const seedVouchers: Voucher[] = [
  { code: 'LIXI2026', discountType: 'fixed', discountValue: 100000, minOrderValue: 500000, maxDiscount: 100000 },
  { code: 'FREESHIP', discountType: 'fixed', discountValue: 30000, minOrderValue: 150000, maxDiscount: 30000 },
  { code: 'GIAM20', discountType: 'percent', discountValue: 20, minOrderValue: 300000, maxDiscount: 200000 },
];

export const seedNotifications: AppNotification[] = [
  {
    id: 'n1',
    title: 'Chao mung den VeloCart',
    message: 'Nhan ma LIXI2026 giam 100K cho don hang dau tien.',
    date: '2026-06-22',
    isRead: false,
    type: 'system',
  },
  {
    id: 'n2',
    title: 'Flash sale cong nghe',
    message: 'Nhieu san pham dien thoai, laptop va phu kien dang giam sau hom nay.',
    date: '2026-06-22',
    isRead: true,
    type: 'promo',
  },
];

export const seedOrders: Order[] = [];

export const seedUser: UserProfile = {
  name: 'Nguyen Van Hung',
  phone: '0912345678',
  email: 'vanhung.nguyen@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
};
